---
version: 1
search_paths:
  - PACKAGE_PATH\examples\plugins\physics2d_example.py
  - PACKAGE_PATH\examples\plugins\pygame_example.py
dependencies:
  - name: Transform2DPlugin
    version: "1.0.0"
    apis:
      - name: NdarrayComponentManagerAPI
        version: "1.0.0"
  - name: Physics2DPlugin
    version: "1.0.0"
    apis:
      - name: SystemAPI
        version: "0.0.0"
