---
version: 1
search_paths:
  - PACKAGE_PATH\examples\plugins\engine_examples.py
dependencies:
  - name: TestPlugin
    version: "1.0.0"
    apis:
      - name: TestPluginAPI
        version: "1.0.0"
  - name: TestSystemPlugin
    version: "1.0.0"
    apis:
      - name: SystemAPI
        version: "0.0.0"
